# This is a basic workflow to help you get started with Actions 

name: SBOMGenerator 

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:  
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup cpp
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 6.0
      - name: Generate SBOM
        run: |
          ls
          curl -Lo $RUNNER_TEMP/sbom-tool https://github.com/microsoft/sbom-tool/releases/latest/download/sbom-tool-linux-x64
          chmod +x $RUNNER_TEMP/sbom-tool
          $RUNNER_TEMP/sbom-tool generate -b . -bc . -pn Test -pv 1.0.1 -ps Elijah_Nunez -nsb http://workflowtest/ -v Verbose
          ls ./_manifest/spdx_2.2/
          cat ./_manifest/spdx_2.2/manifest.spdx.json
      #Build and upload Artifacts
      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          path: ./_manifest
